import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { map } from 'rxjs';
import { IAppState, incrementaContador, decrementaContador, defineContador } from './store/app.state';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  title = 'projectNgRx';
  counter$ = this.store.select('app').pipe( map(e => e.counter));


  constructor(
    private store: Store<{app: IAppState}>){}


    definirContador(contador: string){
      const valorTratato = parseFloat(contador);
      console.log(valorTratato);

      this.store.dispatch(defineContador({ payload: valorTratato}))
    }


  incrementaContador(){
    this.store.dispatch(incrementaContador())
  }

  decrementaContador(){
    this.store.dispatch(decrementaContador())
  }

}



// Generated by https://quicktype.io

export interface ITodo {
  userId:    number;
  id:        number;
  title:     string;
  completed: boolean;
}
